
package com.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "K2CallBackService", targetNamespace = "http://service.k2callback.webservice.workorder.hypersmart.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface K2CallBackService {


    /**
     * 
     * @param id
     * @param state
     * @param processState
     * @return
     *     returns com.demo.CommonResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateK2ProcStatus", targetNamespace = "http://service.k2callback.webservice.workorder.hypersmart.com/", className = "com.demo.UpdateK2ProcStatus")
    @ResponseWrapper(localName = "updateK2ProcStatusResponse", targetNamespace = "http://service.k2callback.webservice.workorder.hypersmart.com/", className = "com.demo.UpdateK2ProcStatusResponse")
    public CommonResult updateK2ProcStatus(
            @WebParam(name = "ID", targetNamespace = "")
                    String id,
            @WebParam(name = "state", targetNamespace = "")
                    String state,
            @WebParam(name = "processState", targetNamespace = "")
                    String processState)
        throws Exception_Exception
    ;

}
